### ISSUE TITLE
`units.HXprocess` not working when `Stream.h` is called

### ISSUE THREAD

**Issue by BenPortner** [BioSTEAMDevelopmentGroup/biosteam#109]
HI @yoelcortes,

For some reason `biosteam.units.HXprocess` does not work properly when `Stream.h` is called before simulating. For example:

``` python
import biosteam as bst

bst.settings.set_thermo(["H2"])

warm_in = bst.Stream(H2=0.5, T=80, P=80e5, phase='g')
cold_in = bst.Stream(H2=0.5, T=29, P=1e5, phase='g')

# warm_in.h <- uncommenting this line causes Q=0 
# cold_in.h <- uncommenting this line causes a RuntimeError
# no problem if keeping both lines commented 

HX = bst.units.HXprocess(ins=(cold_in, warm_in))
HX.simulate()

print(HX.show())
```

**Comment by yoelcortes** [comment]
Thanks for submitting the issue! It had to do with a cache bug in thermosteam. I fixed the bug and added some tests in thermosteam (along with some improvements in the code).

Unfortunately, github seems to be caching fluids so the tests cannot be run in CI. Not sure how to fix it, but I believe github loses the package cache after about 4 days if I remember correctly. All tests are still passing locally.
