### ISSUE TITLE
Incorrect `Mixer` outlet pressure

### ISSUE THREAD

**Issue by BenPortner** [BioSTEAMDevelopmentGroup/biosteam#115]
The `biosteam.units.Mixer` class does currently not calculate outlet pressures correctly:

```python
import biosteam as bst
bst.settings.set_thermo(["CH4"])

s1 = bst.Stream(CH4=1, T=300, P=1e5, phase="g")
s2 = bst.Stream(CH4=1, T=400, P=1e5, phase="g")
mixer = bst.Mixer(ins=(s1,s2), rigorous=True)
mixer.simulate()
print(mixer.outs[0].P) # prints 101325, should be 1e5
```

For `rigorous=True`, the outlet pressure is always 1 atm because `self.pressure` is never calculated. In all other cases `self.P = min([i.P for i in others])`, which also seems incorrect. For ideal mixtures, the outlet pressure should be the mole-weighted average pressure `sum(n_i*P_i)/sum(n_i)`. For real mixtures, I am not sure how to calculate the outlet pressure correctly.

**Comment by BenPortner** [comment]
@yoelcortes that makes sense. Thanks for the hint to the doc. I must have overlooked this part 🙃 Thanks for the quick fix, too!

**Comment by yoelcortes** [comment]
@BenPortner, yeah, that hint in the tutorial is easy to miss and I am thinking it should to be in the docstrings too. I went ahead and added a note on this to the docstring of the mixer and the Stream.mix_from method.

Thanks again!
