### ISSUE TITLE
Temperature of heating utility agents

### ISSUE THREAD

**Issue by yalinli2** [BioSTEAMDevelopmentGroup/biosteam#129]
Hi @yoelcortes , @jiananf2 is designing an HTL system where multiple unit operations would need pretty high T/P (highest one is a hydrotreating unit at 405°C I think), but none of the `UtilityAgent` in biosteam can currently reach that temperature.

I'm wondering how the temperature for those agents were decided? E.g., now
```python
>>> import biosteam as bst
>>> for ha in bst.HeatUtility.heating_agents:
...     print(ha.ID, ha.T)
low_pressure_steam 412.189
medium_pressure_steam 454.77
high_pressure_steam 508.991
```
were 412.189/454.77/508.991 from Perry or other books? I think there are cases where we just change the temperature, e.g., in the cornstover biorefinery:
https://github.com/BioSTEAMDevelopmentGroup/Bioindustrial-Park/blob/5cfb8f34d314412fc63490ab627473a6b69b05b2/biorefineries/cornstover/_process_settings.py#L45
```python
    _ha = bst.HeatUtility.get_heating_agent('low_pressure_steam')
    _ha.heat_transfer_efficiency = 0.90
    _ha.T = 529.2
    _ha.P = 44e5
    _ha.regeneration_price = 0.
```

Thank you!

**Comment by yoelcortes** [comment]
@yalinli2, @jiananf2, 

The steam pressures come from Warren Seiders's product and process design principles. The temperature is the bubble point temperature.  Steam utilities work by transferring heat as they condense. For temperatures above the critical point (370 C), you'll need to define another heating agent (not water) with a higher critical point... But a better option is probably to just natural gas (or any other fuel) directly. Heat utilities do not support heat transfer by combustion yet, so you'll need to hard code the energy balance and set the natural gas as an inlet stream.

Hope this helps,
Thanks!

**Comment by yoelcortes** [comment]
Also, you may also want to consider the cost of the compressor to pump air for the natural gas to combust.

**Comment by yalinli2** [comment]
sounds good thanks for the inputs! I'll let this issue open for some time till we figure out a good way to handle this and then follow up, thanks!

**Comment by yalinli2** [comment]
Just a note that Jianan has added hot oil as a new utility agent - we'll submit a PR when we are comfortable with the assumptions and clean up codes.

**Comment by jiananf2** [comment]
The hot oil is not ready to add yet. You can close this issue and we can add it later if needed.

**Comment by yalinli2** [comment]
Thanks @jiananf2 for the note, can you briefly list why it was not ready (documentation? some flaws?)?

**Comment by jiananf2** [comment]
@yalinli2, the regeneration price is unknown. In the HTL system, we used CHP to regenerate heat utilities, so it does not matter. But we need to determine the price before it's ready. I could probably try to find a price later.

**Comment by yalinli2** [comment]
oh I see, makes sense, I'll close this issue for now, thanks!
