### ISSUE TITLE
Centrifuge LLE is giving attribute error.

### ISSUE THREAD

**Issue by ard3051997** [BioSTEAMDevelopmentGroup/biosteam#13]
from biosteam import Stream
from biosteam.units import Centrifuge_LLE
from biorefineries.lipidcane import species

# Set up stream
Stream.species = species.biodiesel_species
feed = Stream(Lipid=1, Methanol=51, Glycerol= 9, Biodiesel=27, T=333.15)

# Set up centrifuge
C1 = Centrifuge_LLE(ID='C1',ins = feed, outs = ('light', 'heavy'), species_IDs=('Lipid', 'Methanol', 'Biodiesel'), split=(1, 0.5, 1), solvents=('Glycerol',),solvent_split=(0.05))

# Run all methods
C1.simulate()

# See all results
C1.diagram()
C1.show(T='degC', P='atm', fraction=True)

Error - 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Abhishek D\source\repos\Biorefinery Simulation\env_2_new\lib\site-packages\biosteam\units\_centrifuge_LLE.py", line 64, in __init__
    Unit.__init__(ID, ins, outs)
  File "C:\Users\Abhishek D\source\repos\Biorefinery Simulation\env_2_new\lib\site-packages\biosteam\_unit.py", line 189, in __init__
    self._init_ins(ins, species)
AttributeError: 'str' object has no attribute '_init_ins'

**Comment by yalinli2** [comment]
I think Centrifuge_LLE is still under development, it is recommended to use SplitCentrifuge_LLE for now
(See the reply in #12).

**Comment by yoelcortes** [comment]
The centrifuge modeled by liquid-liquid equilibrium has been added to BioSTEAM! There are a couple of name changes. The centrifuge modeled by equilibrium is called LLECentrifuge, while the centrifuge modeled by user-specified components splits is called LiquidsSplitCentrifuge.

https://biosteam.readthedocs.io/en/latest/units/LLECentrifuge.html
