### ISSUE TITLE
MixTank costing change

### ISSUE THREAD

**Issue by yalinli2** [BioSTEAMDevelopmentGroup/biosteam#135]
Hi @yoelcortes , I noticed significant change in the cost of tanks from ~ a week ago to the newest biosteam, mainly

```python
import biosteam as bst
bst.settings.set_thermo((bst.Chemical('H2O'),))
s = bst.Stream('s', H2O=1410, units='kg/hr')
M2 = bst.MixTank('M2', ins=s, tau=2)
M2.simulate()
```
Here's what I got now:
<img width="392" alt="Screen Shot 2022-10-24 at 4 22 37 PM" src="https://user-images.githubusercontent.com/49011373/197632108-2d9cd1df-2747-4510-8cba-cabed7649e80.png">

but here's what @joyxyz1994  got (she's using older biosteam):
![image](https://user-images.githubusercontent.com/49011373/197632313-dd081dca-cf32-482d-9fb3-595bd89fc0c4.png)

is this some intentional change? Thanks!

**Comment by yoelcortes** [comment]
Thanks for the bug report! The issue had to do with name changes (Tanks to Tank) and cost factors. It should be fixed now:

```python
>>> import biosteam as bst
>>> bst.settings.set_thermo((bst.Chemical('H2O'),))
>>> s = bst.Stream('s', H2O=1410, units='kg/hr')
>>> M2 = bst.MixTank('M2', ins=s, tau=2)
>>> M2.simulate()
>>> M2.results(include_installed_cost=True)
Mix tank                                  Units       M2
Electricity              Power               kW    0.348
                         Cost            USD/hr   0.0272
Design                   Residence time      hr        2
                         Total volume       m^3     3.54
Purchase cost            Tank               USD 2.53e+04
Total purchase cost                         USD 2.53e+04
Installed equipment cost                    USD 4.18e+04
Utility cost                             USD/hr   0.0272
```
Thanks!
