### ISSUE TITLE
Contributing to master branch

### ISSUE THREAD

**Issue by yoelcortes** [BioSTEAMDevelopmentGroup/biosteam#138]
@sarangbhagwat, @yalinli2, @joyxyz1994,

I have added a "protection" to the master branches of both BioSTEAM and thermosteam that only allows pull requests to merge with the master branch, so directly pushing the master branch will not work anymore. I feel that the BioSTEAM user base has grown quite big (so many universities depending on it) and we should have a little extra care to make sure all results are accurate. I have introduced many bugs in the past that go unnoticed, so hopefully having others review will help avoid issues that are hard to catch. 

Note that same rules apply to me, so I will also need to go through pull requests to add things to the master branch. 

Thanks!

**Comment by yalinli2** [comment]
Thanks @yoelcortes ! I'm all for it!

**Comment by sarangbhagwat** [comment]
Sounds good! Thanks @yoelcortes!
