### ISSUE TITLE
Power consumption default in AeratedBioReactor needs more detail

### ISSUE THREAD

**Issue by siddharthab** [BioSTEAMDevelopmentGroup/biosteam#171]
In AeratedBioReactor (and now GasFedBioReactor), I was not able to find the basis for the default value of kw/m3.
 https://github.com/BioSTEAMDevelopmentGroup/biosteam/blob/1e1b2029ec741fbe05fc8d47f90149961ed24488/biosteam/units/stirred_tank_reactor.py#L416

In similar process simulations elsewhere, I have seen people use ~1 kw/m3 even for aerated bioreactors, just like biosteam does for stirred tank reactors.

A reference citation or some more detail on this constant would be helpful.

**Comment by yoelcortes** [comment]
I have been meaning to add references to this new unit. I just added them for the aerated bioreactor design. The default value comes from Seider's Product and Process Design Principles (ref 1) and it's similar to values in the other references . 

From my experience, 1 kw/m3 is too high for an aerated bioreactor, where much of the mixing comes from compressed air. 
Regardless, this a design choice which can be optimized (less mixing power means greater air flow rate to meet the oxygen uptake rate).

Thanks!

**Comment by siddharthab** [comment]
Thanks for such a quick resolution!
