### ISSUE TITLE
Biogas upgrading

### ISSUE THREAD

**Issue by MaryTutuola** [BioSTEAMDevelopmentGroup/biosteam#178]
Hello, I want to know if Biosteam can be used to simulate a water-scrubbing system, and how to go about it if it can.

**Comment by yoelcortes** [comment]
Hello! 

If you have an estimate of the stage efficiency, you can use BioSTEAM's Adsorption column to model it by thermodynamic equilibrium (https://biosteam.readthedocs.io/en/latest/API/units/distillation.html#biosteam.units.distillation.AdiabaticMultiStageVLEColumn). Then you'll need to add the cost of packing.

However, rigorous simulation of water-scrubbing systems for biogas are modeled by differential mass transfer. Such a model has not been contributed to biosteam yet, but BioSTEAM can certainly help you model it (https://biosteam.readthedocs.io/en/latest/tutorial/Inheriting_from_Unit.html). 

Hope this helps,
Thanks!
