### ISSUE TITLE
Bug: unit design decorator

### ISSUE THREAD

**Issue by yalinli2** [BioSTEAMDevelopmentGroup/biosteam#19]
**Describe the bug**
The script was not updated to work with the new thermosteam functions, leading to a TypeError. 
I believe the origin code in biosteam.units.decorators._design of:
```python
moisture = sum([i.get_flow(units, IDs='7732-18-5') for i in ins])
```
should be replaced with 
```python
moisture = sum([i.get_flow(units, key='7732-18-5') for i in ins])
```
I tried this and it fixed the problem

**To Reproduce**
I found this when trying to import the cornstover biorefinery:
```python
from biorefineries.cornstover.system import cornstover
```

**Screenshots**
Screenshot for error:
<img width="624" alt="Error" src="https://user-images.githubusercontent.com/49011373/77457676-03565680-6dcb-11ea-8828-9f0fb76ebdc8.png">

Fixing the code:
<img width="624" alt="Fix" src="https://user-images.githubusercontent.com/49011373/77457737-18cb8080-6dcb-11ea-88a8-0b53d7924d6b.png">

<img width="624" alt="Fixed" src="https://user-images.githubusercontent.com/49011373/77457933-60520c80-6dcb-11ea-931d-a172384efcee.png">

**Environment**
 - Python: v3.7.6
 - OS: macOS Catalina 10.15.3
 - BioSTEAM: v2.6.7
 - thermosteam: v0.6.8
 - biorefineries: v2.6.2

**Comment by yoelcortes** [comment]
Thanks! It'll be fixed soon :)
