### ISSUE TITLE
Sub class modelling of CSTR

### ISSUE THREAD

**Issue by Omotola94** [BioSTEAMDevelopmentGroup/biosteam#196]
**Describe the bug**
Encountered series of bugs,I believe it is with my sub class modelling of CSTR.

**To Reproduce**
[Reactor model.txt](https://github.com/BioSTEAMDevelopmentGroup/biosteam/files/14618217/Reactor.model.txt)

**Expected behavior**
I am expecting the reactor to give product based on the reaction provided to run in a continuous method, just like the continuous fermentation example

**Actual behavior**
Full trace back, as
![Screenshot 2024-03-15 112814](https://github.com/BioSTEAMDevelopmentGroup/biosteam/assets/160638950/f1c79f4d-2483-4c14-bc7c-9f780a834bce)
 text or a screenshot

**Version**
 - 2.43.1-I am running it on google colab

**Additional context**
In addition, I am finding it difficult to add auxiliary units for example recirculation pump and an exchanger.

**Comment by yoelcortes** [comment]
@Omotola94, 

On first impression, the code looks good except for this one line:

```python
effluent.mix_from(self.ins[0])  # Mix feed with effluent
```

Note that `mix_from` expects a list/iterable of streams, not a single Stream object. You can replace this line with:

```python
effluent.copy_like(self.ins[0]) # Or effluent.mix_from([self.ins[0]]) 
```

I'm also going to add a better error message for this case (when users try to use a stream like an iterable).

Let me know if you run into anything else!
Thanks,

**Comment by Omotola94** [comment]
Thank you.
I just ran the code and  i got the error above 'int' object has no attribute 'lower'

**Comment by Omotola94** [comment]
Thank you,
![Screenshot 2024-03-15 161754](https://github.com/BioSTEAMDevelopmentGroup/biosteam/assets/160638950/95a0b839-c95f-477f-87fa-1f02a6c00f23)
I encountered this error, If you can please shed more light on line 327-329 and suggest a code to get pass through this.
