### ISSUE TITLE
Missing essential unit operation models

### ISSUE THREAD

**Issue by yoelcortes** [BioSTEAMDevelopmentGroup/biosteam#2]
Any help in developing the following essential unit operations would be greatly appreciated:
* [x] Compressor (added 8/6/2022)
* [x] Turbine
* [x] Fenske-Gilliland-Underwood shortcut column (added 3/22/2020)
* [x] Rigorous heat exchanger for heat integration (added 6/6/2020)
* [x] Multi-component distillation models (preferably MESH equation based; Completed 12/17/2023)
* [x] Kinetic fermentation models (because of the large number of models out there, it is out of the scope of BioSTEAM; but models may be contributed to the bioindustrial-park)
* [x] Centrifuge modeled by liquid-liquid equilibrium (added 3/27/2020)
* [x] Settler modeled by liquid-liquid equilibrium (added 6/6/2020)

Please visit the ["Inheriting from Unit"](https://biosteam.readthedocs.io/en/latest/tutorial/Inheriting_from_Unit.html) section in the docs for how to create a Unit operation. Make sure to read the ["Developer's guide"](https://biosteam.readthedocs.io/en/latest/CONTRIBUTING.html) before making any pull request. Briefly, concise and thorough documentation with full references, and passing biorefinery and unit operation tests are required for every contribution.

**Comment by yoelcortes** [comment]
The Fenske-Gilliland-Underwood shortcut column is coming soon! Some documentation and tests need to be added. Expect BioSTEAM v2.6 to be out in about a week with the ShortcutColumn unit operation.

**Comment by yalinli2** [comment]
Hey Yoel, I thought the current `Fermentation` class had kinetic models? Is that still under development?

**Comment by yoelcortes** [comment]
Yeah... The `Fermentation` unit for conventional ethanol has a kinetic model but, if I remember correctly, it gives overly optimistic estimates for sugarcane juice. It would be nice to have accurate kinetic models for cellulosic and conventional ethanol with different strains. None of these are under development, but contributions here are definitely welcome!

**Comment by yalinli2** [comment]
Ah gotcha, thanks!
