### ISSUE TITLE
Mismatching info for `HeatUtility` objects

### ISSUE THREAD

**Issue by yalinli2** [BioSTEAMDevelopmentGroup/biosteam#21]
**Describe the bug**
Sometimes,  `HeatUtility.flow` and  `HeatUtility.inlet_utility_stream` / `HeatUtility.outlet_utility_stream` flow information aren't matching, but this doesn't appear to be affecting results, only causing confusion in display.

**To Reproduce**
This is most easily seen in the cornstover biorefinery. See the screenshot, the flow of `low_pressure_steam` should be negative, `BT.heat_utilities[1].flow` gives the correct flow, but `BT.heat_utilities[1]` gives the opposite.

I think this is because the `inlet_utility_stream` and `outlet_utility_stream` flows are not correct, which stems from the `reverse` function. In that function, `inlet_utility_stream` and `outlet_utility_stream` are swapped, probably their flow should multiply by -1 instead?

_However, I'm not sure whether there are other cache problems with the display_

**Screenshots**
Output
<img width="604" alt="Screen Shot 2020-04-29 at 5 44 49 PM" src="https://user-images.githubusercontent.com/49011373/80654505-ff5cca80-8a41-11ea-88a4-60dacdae2102.png">

Code for `reverse` function
<img width="814" alt="Screen Shot 2020-04-29 at 5 48 49 PM" src="https://user-images.githubusercontent.com/49011373/80654507-0257bb00-8a42-11ea-9a5e-fc981d950809.png">

**Environment**
 - Python: v3.7.6
 - OS: macOS Catalina v.10.15.4
 - BioSTEAM: v.2.15.3
 - thermosteam: v.0.15.6
 - biorefineries: v2.10.1

Thanks!!!

**Comment by yoelcortes** [comment]
Ahh, so in the Ipython display (In [3]) should be negative. I'll patch this up. The inlet_utility_stream and outlet_utility stream flows are correct, stream flows are always positive. The negative sign on flow just denotes that we are producing a utility (not consuming). This is reflected in the utility streams as well because they are flipped (as you mentioned).

**Comment by yalinli2** [comment]
Yes for [3] and agree that flow stream should be positive, thanks!
