### ISSUE TITLE
Issue about Absorber and Stripper unit simulation

### ISSUE THREAD

**Issue by 1226Wang1226** [BioSTEAMDevelopmentGroup/biosteam#211]
Q1:
After the two input streams of U104 pass through the Absorber, most of the carbon dioxide should dissolve in water. The compositions of the two output streams should be as I set in the code, namely rich_solution and gas_out. However, I did not perform the actual simulation of the Absorber here but directly set the two output streams. In reality, these two output streams should result from the Absorber simulation. Therefore, the output streams here are provided for reference only.

Q2:
After rich_solution passes through the Flash unit, there should theoretically still be some residual gases in the liquid. A typical composition could be as follows:
CO₂ = 377.11, CH₄ = 0.67, H₂S = 0.22, N₂ = 0.002, O₂ = 0.009, H₂O = 84364 (Units: kg/hr).
However, after running the simulation, the output stream from the Flash unit contains only water.

Q3:
After the Stripper operates, the output streams should include two parts: one is a liquid stream containing only water, and the other is a gas stream, gas_exit.

Here is my code:

import biosteam as bst
from biosteam import units, facilities
import numpy as np

bst.nbtutorial()
bst.main_flowsheet.set_flowsheet('Water_scrubbing_biogas')
chemicals = bst.Chemicals(
    ['Water',
     bst.Chemical('CO2',phase='g'),
     bst.Chemical('CH4',phase='g'),
     bst.Chemical('H2S',phase='g'),
     bst.Chemical('N2',phase='g'),
     bst.Chemical('O2',phase='g')]
)
bst.settings.set_thermo(chemicals)
raw_biogas=bst.Stream(
    'raw_biogas',
    CH4=214.84,
    CO2=382.8,
    H2S=0.228,
    N2=3.12,
    O2=3.57,
    T=298.15,
    P=101325,
    total_flow=500,
    units='kg/hr',
    phase='g'
)
                        
water=bst.Stream('water')
gas_rec=bst.Stream('gas_rec',
                   )
air_in=bst.Stream('air_in',
                 N2=987.91,
                 O2=299.96,
                 units='kg/hr',
                 phase='g'
)
sol_fl = bst.Stream('sol_fl')
rich_solution = bst.Stream('rich_solution',
                           CO2=614.26,
                           CH4=11.29,
                           H2S=0.27,
                           N2=0.073,
                           O2=0.16,
                           H2O=84365,
                           units='kg/hr',
                           phase='l',
                           P=1e6
                          )
gas_out=bst.Stream('gas_out',
                   CO2=5.69,
                   CH4=214.17,
                   H2S=0.0000028,
                   N2=4.38,
                   O2=4.31,
                   H2O=0.56,
                   units='kg/hr',
                   phase='g'
                  )
gas_exit=bst.Stream('gas_exit',
                    CO2=377.11,
                    CH4=0.67,
                    H2S=0.22,
                    N2=986.62,
                    O2=299.21,
                    H2O=22.05,
                    units='kg/hr',
                    phase='g'
                   )
cooledbg=bst.Stream('cooledbg')
gasrec=bst.Stream('gasrec')
fresh_water=bst.Stream('fresh_water',water=2000,units='kg/hr')
freshwater=bst.Stream('freshwater')
process_water=bst.Stream('process_water')
water_rec=bst.Stream('water_rec', water=82370,units='kg/hr')
U101 = units.IsentropicCompressor('U101',raw_biogas, outs='compressed_raw_biogas_0',P=800000, eta=0.75)
hx2=units.HXutility('HX2', ins=U101-0, outs='ccrb0', T=298.15)
hx3=units.HXutility('HX3',ins=gasrec, outs='cooledgasrec', T=298.15)
U102 = units.Mixer('U102',ins=(hx2-0,hx3-0),outs='mixed_raw_biogas')
U103=units.IsentropicCompressor('U103',U102-0,outs='comrepssed_raw_biogas',P=1000000,eta=0.75)

P1=units.Pump('P1',ins=fresh_water, outs='freshwater',P=1e6)
hx1=units.HXutility('HX1',ins=U103-0, outs=cooledbg,T=298.15)
U104=units.Absorber('U104',N_stages=9,ins=[cooledbg,P1-0],
                    solute="Water", outs=(gas_out,rich_solution),P=1e6)
C1=units.IsentropicCompressor('C1',gas_rec, outs=gasrec, P=800000)
U105=units.Flash('U105',U104-1,outs=[gas_rec, sol_fl],
                 P=300000, T=293)
U107=units.Stripper('U107', ins=[sol_fl,air_in],solute="Water",
                    outs=(gas_exit,'liq_str'),P=101325,N_stages=9
                   )
U109=units.Splitter('U109',U107-1,split=0.1,outs=['liq_spl','liq_out'])
U110=units.Pump('U110',U109-0,outs=water_rec,P=1e6)

U101.simulate()
hx2.simulate()
U105.simulate()
U110.simulate()
P1.simulate()
C1.simulate()
hx3.simulate()
U102.simulate()
U103.simulate()
hx1.simulate()

bst.main_flowsheet.diagram(format='png')

And my python version is 3.12.7, and i did all my work on jupyter notebook.

<img width="511" alt="WechatIMG55" src="https://github.com/user-attachments/assets/8c97599a-56cf-490b-a8ef-1077008f9209" />
<img width="1044" alt="WechatIMG51" src="https://github.com/user-attachments/assets/7f1be553-a86f-46ec-ad68-935d77bd42f8" />

Apart from the specific issues I mentioned earlier, I would like to know whether my current approach to building a model using BioSTEAM is reasonable in terms of overall direction. Additionally, if possible, I would appreciate it if you could point out any other potential problems or areas for improvement in the code.

I sincerely thank you for taking the time to review my work and for any assistance you can provide. Your guidance and expertise mean a great deal to me, and I am truly grateful for your help!!!

**Comment by yoelcortes** [comment]
Hi! This is great code (good direction). You had one bug: setting the phase of a chemical (like Chemical('CO2', phases='g')) makes it so that it will **always** remain a gas and excludes it for vapor-liquid equilibrium. Also, unfortunately, BioSTEAM does not do well with modeling equilibrium of fluids close to or at supercritical conditions (like CO2 and N2); more development is needed... This leads to issues in modeling columns. 

I made some edits to the code so that it can work as a preliminary model by assuming the adiabatic column has a constant temperature (which is OK in this situation). Please "pip install biosteam==2.49.1" to get it to work.

Unfortunately the exit flows does not match well with your benchmarks (too much CO2 not adsorbed). But you can always add a specification to the unit to override the mass balance with data. 

```python
import biosteam as bst
bst.main_flowsheet.set_flowsheet('Water_scrubbing_biogas')
chemicals = bst.Chemicals(
    ['Water', 'CO2', 'CH4', 'H2S', 'N2', 'O2']
)
bst.settings.set_thermo(chemicals)
bst.settings.mixture.include_excess_energies = True # More rigorous results considering high-pressures
raw_biogas=bst.Stream(
'raw_biogas',
CH4=214.84,
CO2=382.8,
H2S=0.228,
N2=3.12,
O2=3.57,
T=298.15,
P=101325,
total_flow=500,
units='kg/hr',
phase='g'
)

water=bst.Stream('water')
gas_rec=bst.Stream('gas_rec',
)
air_in=bst.Stream('air_in',
N2=987.91,
O2=299.96,
units='kg/hr',
phase='g'
)
sol_fl = bst.Stream('sol_fl')
rich_solution = bst.Stream('rich_solution',
CO2=614.26,
CH4=11.29,
H2S=0.27,
N2=0.073,
O2=0.16,
H2O=84365,
units='kg/hr',
phase='l',
P=1e6
)
gas_out=bst.Stream('gas_out',
CO2=5.69,
CH4=214.17,
H2S=0.0000028,
N2=4.38,
O2=4.31,
H2O=0.56,
units='kg/hr',
phase='g'
)
gas_exit=bst.Stream('gas_exit',
CO2=377.11,
CH4=0.67,
H2S=0.22,
N2=986.62,
O2=299.21,
H2O=22.05,
units='kg/hr',
phase='g'
)
cooledbg=bst.Stream('cooledbg')
gasrec=bst.Stream('gasrec')
fresh_water=bst.Stream('fresh_water', water=2000, units='kg/hr')
process_water=bst.Stream('process_water')
water_rec=bst.Stream('water_rec', water=82370,units='kg/hr')

with bst.System() as sys:
    U101 = bst.IsentropicCompressor('U101',raw_biogas, outs='compressed_raw_biogas_0',P=800000, eta=0.75)
    hx2=bst.HXutility('HX2', ins=U101-0, outs='ccrb0', T=298.15)
    hx3=bst.HXutility('HX3',ins=gasrec, outs='cooledgasrec', T=298.15)
    U102 = bst.Mixer('U102',ins=(hx2-0,hx3-0),outs='mixed_raw_biogas')
    U103=bst.IsentropicCompressor('U103',U102-0,outs='comrepssed_raw_biogas',P=1000000,eta=0.75)
    P1=bst.Pump('P1',ins=fresh_water, outs='freshwater',P=1e6)
    hx1=bst.HXutility('HX1',ins=U103-0, outs=cooledbg,T=298.15)
    U104 = bst.Absorber(
        'U104', T=298.15,
        N_stages=9, ins=[P1-0, cooledbg], solute="CO2", outs=(gas_out,rich_solution), 
        P=1e6
    )
    raw_biogas.set_feed_priority(0) # Make simulations start here.
    
    # # BioSTEAM starts simulation from the feed with the largest flow.
    # # So alternatively, empty other streams and populate during simulation.
    # fresh_water.empty() 
    # @U104.add_specification(run=True, impacted_units=[P1])
    # def adjust_fresh_water_flow():
    #     fresh_water.imass['Water'] = 2000 
                    
    C1=bst.IsentropicCompressor('C1',gas_rec, outs=gasrec, P=800000)
    U105=bst.Flash('U105',U104-1,outs=[gas_rec, sol_fl],
    P=300000, T=293)
    U107=bst.Stripper(
        'U107', ins=[sol_fl,air_in], solute="CO2",
        outs=(gas_exit,'liq_str'), P=101325, N_stages=9, T=293,
    )
    U109=bst.Splitter('U109',U107-1,split=0.1,outs=['liq_spl','liq_out'])
    U110=bst.Pump('U110',U109-0,outs=water_rec,P=1e6)

sys.simulate()
sys.diagram(number=True, kind='cluster') # This shows you the order of simulation and the recycle loops.
```

I hope this helps,
Thanks!

**Comment by 1226Wang1226** [comment]
@yoelcortes Thank you sososo much!!! The code is now running, but there’s a new issue: U104 was supposed to be the absorber, but it’s now showing as the stripper, while U107 is showing the opposite. Why is this happening?
<img width="475" alt="图片1" src="https://github.com/user-attachments/assets/0819cd20-dcca-46e7-be78-4f0f7ce3f240" />
How does BioSTEAM determine what type of unit a given unit operation is? I initially thought it was based on the unit name, but now it seems like that’s not the case. Could you clarify how the unit type is defined or recognized in BioSTEAM?

Thank you again for your patience and all the help you’ve provided!

**Comment by yoelcortes** [comment]
@1226Wang1226, stripping is when the solute (in this case CO2) is moves from the gas to the liquid phase. Absorption is when the solute moves from the liquid to the gas phase. Right?

**Comment by 1226Wang1226** [comment]
@yoelcortes Nope, absorption is when CO2 moves from the gas to the liquid phase, and stripping is when CO2 moves from the liquid to the gas phase. Just like this:
<img width="428" alt="image" src="https://github.com/user-attachments/assets/38036dcc-c16f-41fd-89f0-fb98b686f797" />

**Comment by yoelcortes** [comment]
Please "pip install biosteam==2.49.2" for the name fix.

Thanks,

**Comment by 1226Wang1226** [comment]
thank u so much again!!😊
