### ISSUE TITLE
Best practice for evaluating TEA parameters

### ISSUE THREAD

**Issue by yalinli2** [BioSTEAMDevelopmentGroup/biosteam#23]
**Description**
Assume I want to evaluate how minimum product selling price (MPSP) changes with internal rate of return (IRR) under uncertainty, and I want to depict this using a figure where the x-axis is IRR, y-axis is MPSP, and the IRR vs. MPSP correlation is a curve with error band to express uncertainty (similar to Figure 4 in the paper Cortes-Peña et al., ACS Sustainable Chem. Eng. 2020, 8 (8), 3302–3310).

I can use the `evaluate_across_coordinate` function for `Model` object, but I'm wondering if this is the best practice? I ask because unlike Figure 4 in the paper where the change of feedstock lipid content affects the system, change of TEA parameters like IRR won't affect the system. So for each of the Monte Carlo scenario, there's no need to re-simulate the system to get the MPSP, re-calculating the cashflow should be enough. 

My impression from reading the document is that BioSTEAM creates `Block` objects that only simulate the system downstream of the change, so I'm wondering if for my question, this means that only the cashflow will be re-calculated when change IRR (which is what we want)?
 
Thanks!!!

**Comment by yoelcortes** [comment]
Great question, in the `evaluate_across_coordinate` method, each Monte Carlo is evaluated in sequence. So with every change in the coordinate (in this case the IRR) all samples are evaluated. So we are doing Monte Carlo for coordinate point.

You could save a lot of time if you perform this evaluation without using the `evaluate_across_coordinate` method. Here is some code you could use:

**Comment by yalinli2** [comment]
Oh yeah indeed setting IRR as metrics is a much better/ingenious way! Thanks!!!

**Comment by yalinli2** [comment]
A side question that almost drove me crazy, I don't think it's caused by BioSTEAM, but would really appreciate your help.

So I'm wondering if you know why this worked:
```python
def create_IRR_metric(IRR):
    def get_IRR_based_MSP():
        # Is it necessary to change all IRRs? Or just IRR for CombinedTEA is enough?
        orgacids_tea.IRR = orgacids_sys_no_boiler_tea.IRR = boiler_sys_tea.IRR = IRR
        return orgacids_tea.solve_price(lactic_acid, orgacids_sys_no_boiler_tea)
    return Metric(f'MSP at IRR={IRR}', get_IRR_based_MSP, 'USD/kg')
```
But this would lead to an error as in the screenshot? (I wanted to use the `int` function so that I wouldn't have some weird numbers like "0.35000000000000003" in the column label).

```python
def create_IRR_metric(IRR):
    def get_IRR_based_MSP():
        orgacids_tea.IRR = orgacids_sys_no_boiler_tea.IRR = boiler_sys_tea.IRR = IRR
        return orgacids_tea.solve_price(lactic_acid, orgacids_sys_no_boiler_tea)
    return Metric(f'MSP at IRR={int(IRR*100)}%', get_IRR_based_MSP, 'USD/kg')
```

<img width="643" alt="Screen Shot 2020-05-12 at 3 03 06 PM" src="https://user-images.githubusercontent.com/49011373/81740912-53fd3e00-9463-11ea-82f1-7576d812d4ea.png">

**Comment by yalinli2** [comment]
Oh BTW, using IRR as metrics indeed is very fast and I do get a pretty plot! 🎉
![Figure 2020-05-12 160408](https://user-images.githubusercontent.com/49011373/81745410-6c248b80-946a-11ea-95c3-fea7c3273ec3.png)

**Comment by yoelcortes** [comment]
A float cannot be converted to an int unless its safe. For example, int(1.0000000001) is not safe and int(1.0) is safe.

Also, biosteam assumes that the metric results are floats (values are stored in arrays). Best if you keep the results as floats.

**Comment by yoelcortes** [comment]
Ahh, just noticed your other question.

Is it necessary to change all IRRs? Or just IRR for CombinedTEA is enough?
We only need to change the CombinedTEA IRR.

Thanks!

**Comment by yoelcortes** [comment]
@yalinli2 I just realized what your error is. You must have multiple metrics with the same name. Try adding more significant figures to the name:
```python
>>> f"IRR={0.01123:.4%}"
'IRR=1.1230%'
```

**Comment by yalinli2** [comment]
I think you meant that I had multiple metrics with the same name so I ran into this error (not that I should have metrics with the same name?)

> @yalinli2 I just realized what your error is. You must have multiple metrics with the same name. Try adding more significant figures to the name:
> 
> ```python
> >>> f"IRR={0.01123:.4%}"
> 'IRR=1.1230%'
> ```

Anyway, thanks for the clue! I was initially confused by this because I printed the length of `var_indices(self._metrics)` and `values` and they were the same, then I realized the problem is in pandas. When the error was triggered, my metrics looked like this with four 28% (length=44):

<img width="418" alt="Screen Shot 2020-05-13 at 8 45 33 AM" src="https://user-images.githubusercontent.com/49011373/81825138-e05b3f80-94fb-11ea-81e4-3b1cfa1fc5cb.png">

Whereas using orgacids_model_IRR.metrics gave me two 28% (length=42):
<img width="272" alt="Screen Shot 2020-05-13 at 9 36 12 AM" src="https://user-images.githubusercontent.com/49011373/81826332-4ac0af80-94fd-11ea-9b44-dfdbc03a9079.png">

This was because I didn't know `int(0.99)` would return 0 instead of 1 😂. So when generating the IRR metrics, there were two 28% because the latter 28% was supposed to be 29% with a real value of probably 28.9999999+%. At this stage this shouldn't give the error because the metric length was the same (42). But somewhere in pandas, because the real value was lost, so the two metrics became the same and somehow the indices repeated themselves for the two 28%, so the total length of metrics became 44 and therefore triggering the error.

Anyway, spent like six hours to learn the importance of data type, guess still worth it haha. Thanks for the help!!!

**Comment by yalinli2** [comment]
> Ahh, just noticed your other question.
> 
> Is it necessary to change all IRRs? Or just IRR for CombinedTEA is enough?
> We only need to change the CombinedTEA IRR.
> 
> Thanks!

Just a quick note that changing the `CombinedTEA` is enough to get the correct MSP, but NPV of the `CombinedTEA` won't be correct because BioSTEAM calculates combined NPVs by adding up NPV of the individual `TEA` objects in the `CombinedTEA`.  Thanks!!!

<img width="321" alt="Screen Shot 2020-05-13 at 11 21 10 AM" src="https://user-images.githubusercontent.com/49011373/81839306-fa514e00-950c-11ea-90a9-90cb86116812.png">

I've tested with my codes, all MSPs are the same for both cases, but NPVs not. (Also noticed that I'd have to simulate the cashflow for five times to get a good NPV, although I'm not sure whether that has to do with the super large `molar_tolerance` I set for the system for some temporary purposes)

Only changing IRR of `CombinedTEA`:
<img width="520" alt="Screen Shot 2020-05-13 at 11 24 02 AM" src="https://user-images.githubusercontent.com/49011373/81839533-47cdbb00-950d-11ea-8899-751a51d8005c.png">


Changing all IRRs:
<img width="520" alt="Screen Shot 2020-05-13 at 11 26 26 AM" src="https://user-images.githubusercontent.com/49011373/81839565-561bd700-950d-11ea-801b-40282c0a1908.png">

**Comment by yoelcortes** [comment]
@yalinli2 Thanks for finding this bug! I fixed it so that a CombinedTEA object calculates NPV based on its IRR (and not the IRR of its components). 

If you pip install biosteam again, you'd be installing the latest version of thermosteam too. There have been couple of bug fixes:
* No more cache when creating chemicals
* Fixed problem with loading "radical" chemicals from database. This was not a problem for most chemicals we currently use, but some chemicals I am using had this problem. I basically improved the algorithm for identifying chemicals (its faster and shorter too).
* Fixed an energy balance problem, it may or may not be affecting your biorefinery. It actually didn't affect the lipidcane or cornstover results, but in some cases it creates a problem when setting stream enthalpies.

Also, BioSTEAM can now create fitted models  (basically machine learning models) with high R2s (~0.95). But its best if you don't look into this for another month or two, once I got good examples and a tutorial on this.

Thanks!

**Comment by yalinli2** [comment]
> @yalinli2 Thanks for finding this bug! I fixed it so that a CombinedTEA object calculates NPV based on its IRR (and not the IRR of its components). 

Yep it's fixed! Thanks!

Though I think you need to fix some bugs in chemicals.py for the cornstover biorefinery, now there are properties missing for P4O10:
<img width="643" alt="Screen Shot 2020-05-13 at 1 41 09 PM" src="https://user-images.githubusercontent.com/49011373/81852442-a3ee0a80-9520-11ea-95af-777cf89e306b.png">


> If you pip install biosteam==2.17.6, you'd be installing the latest version of thermosteam too. There have been couple of bug fixes:
> 
> * No more cache when creating chemicals

I like this very much! In the past I had to restart the kernel/reload chemicals from time to time because once I modified chemical properties, properties of `tmo.Chemical('ChemicalName')` would be change as well, now `tmo.Chemical('ChemicalName')` gives the properties in the database 👏

> Also, BioSTEAM can now create fitted models (basically machine learning models) with high R2s (~0.95). But its best if you don't look into this for another month or two, once I got good examples and a tutorial on this.

Looking forward to this!!!

**Comment by yoelcortes** [comment]
Ahh, I forgot to update the biorefineries package. Its a pretty easy fix. You can update to biorefineries==0.13.0 and it should work

**Comment by yalinli2** [comment]
Yep it’s fixed! Thanks!
