### ISSUE TITLE
bst._system warning 

### ISSUE THREAD

**Issue by yalinli2** [BioSTEAMDevelopmentGroup/biosteam#32]
The line below will trigger an error - is warning imported from somewhere? I was using biosteam v 2.20.5, but this isn't urgent, you can patch this up in the next update.
https://github.com/BioSTEAMDevelopmentGroup/biosteam/blob/ca825e012684763ecf9dd799a975887777c999f4/biosteam/_system.py#L613

BTW,  thanks for considering adding deprecation warning! It'll help a lot!

**Comment by yoelcortes** [comment]
Just took care of it, thanks!
