### ISSUE TITLE
Reusage of the equipment question.

### ISSUE THREAD

**Issue by DmitryBachin** [BioSTEAMDevelopmentGroup/biosteam#35]
I am trying to replicate the PHA production bioprocess on biosteam.
The process is below.
![image](https://user-images.githubusercontent.com/37069632/89885039-b84aad80-dbca-11ea-9105-260fb7d2937c.png)

What concerns me is the Homogenisation(H301) and Centrifugation (C401). According to the process, they are doing 3 passes on each of these two pieces of the equipment.

I have tried to find out if it is possible to implement it on biosteam. The only way which I see is to make the new objects with zero purchase costs. Is there more elegant way?

**Comment by yoelcortes** [comment]
From the look on this diagram, it seems like T101, T301/T302, T401, and T501 are all surge tanks that allow the process to operate continuously even though we have batch/multi-pass processes like fermentation, homogenisation, and centrifugation.

I think you could implement the unit operations with multiple passes as a new Unit subclass. Although it works as a continuous process, internally, your custom unit can work however you like. For example:

```python
import biosteam as bst
class Homogenizer(bst):
    _units = {'flow rate': 'kg/hr'}    

    def __init__(self, ID="", ins=None, outs=(), thermo=None, passes=3):
        super().__init__(ID, ins, outs, thermo)
        self.passes = passes

    def _design(self):
        feed, = self.ins
        self.design_requirements['flow rate'] = feed.F_mass

    def _cost(self):
        F_mass = self.passes * self.design_requirements['flow rate']
        self.purchase_costs['Homogenizer'] = some_cost_equation(F_mass) 
```

Hope this helps!

**Comment by DmitryBachin** [comment]
Thank you! I will try it and check how it works.

**Comment by DmitryBachin** [comment]
I have checked the article again. Actually, it is a bit more complicated. According to the article text it is like this:
![image](https://user-images.githubusercontent.com/37069632/90018951-05538000-dcae-11ea-8dd6-9c3578725eb1.png)
T301, T302 and T401 are different tanks (T301 and T302 are of similar kinds).
H301 is homogenizer.

So, it is 2 usages of T301, 1 usage of T302 and 3 usages of H301 per round. Of course, I can make it a single object and take everything into account using _design and _cost. However, it might be good to have a way to keep the pieces of the equipment as separate objects.

**Comment by DmitryBachin** [comment]
One more moment related to a similar issue. In the same article([Van Wegen et al. - 1998 - Industrial Production of Polyhydroxyalkanoates Usi copy.pdf](https://github.com/BioSTEAMDevelopmentGroup/biosteam/files/5063332/Van.Wegen.et.al.-.1998.-.Industrial.Production.of.Polyhydroxyalkanoates.Usi.copy.pdf)), there is a schedule of the batch fermentation. 
![image](https://user-images.githubusercontent.com/37069632/90026788-0db0b880-dcb8-11ea-82c4-8954ddcea791.png)
Apparently, they use it for TEA.
So they run two batch fermentors one is emptied in the middle of the other one's run. 
Does biosteam consider parallel running for TEA?

**Comment by yoelcortes** [comment]
BioSTEAM's fermentor (an instance of BatchReactor) works with simple batch scheduling of just the fermentors, you can check out the `size_batch` function (https://github.com/BioSTEAMDevelopmentGroup/biosteam/blob/master/biosteam/units/design_tools/batch.py) for details. In summary, one tank is always being filled file the others are running, cleaning, or unloading.

It does seem like your batch schedule is more complex, but given the connections and the number of passes it should be straight forward to model. All the information you need to give your new unit operations is the connections (including recycle passes) and the number of passes (among other parameters like residence time). If the flows are the same like in T301, T302, and H302 (i.e. no reactions, splitting, or mixing), you don't even need to specify the connections (just use the same inlet/outlet stream for your calculations). In the case of your tank T301, you'll have 2 passes, which means you're tank will have twice the volume for a given residence time (no other calculations are really needed).

Let me know if you run into any problems!

**Comment by yoelcortes** [comment]
I just updated my reply, sorry for the change!
