### ISSUE TITLE
System.save_report raises error for systems without heat utilities

### ISSUE THREAD

**Issue by yalinli2** [BioSTEAMDevelopmentGroup/biosteam#43]
**Describe the bug**
As described in the title, the `save_report` function will raise an error for systems without heat utilities, I think that's because how the heat utility table is created by the `heat_utilities_table` function in biosteam/report/table. Please make it possible for those systems to have reports. Thank you!

**To Reproduce**
Any simple systems will do, for example:
```python
import biosteam as bst

bst.settings.set_thermo(bst.Chemicals(('Water', 'Ethanol')))

s1 = bst.Stream(Water=100, Ethanol=50)
s2 = bst.Stream(Water=100, Ethanol=10)

M1 = bst.Mixer(ins=(s1, s2))
S1 = bst.Splitter(ins=M1-0, split=0.1)

sys = bst.System('sys', path=(M1, S1))

sys.save_report('sys.xlsx')
```

**Expected behavior**
Excel file as system report

**Actual behavior**
*Note: I think you had an extra space between "**" and "Actual behavior" in your .github/ISSUE_TEMPLTE/bug_report.md, it was not rendered correctly so I changed it myself.*
<img width="681" alt="Screen Shot 2020-12-05 at 7 49 10 AM" src="https://user-images.githubusercontent.com/49011373/101244851-60cad300-36ce-11eb-9b2a-6db548648c10.png">

**Version**
 - biosteam v2.21.6

**Comment by yoelcortes** [comment]
fixed! Let me know if anything else is not working :)

**Comment by yalinli2** [comment]
Thanks for checking this out! But unfortunately it's not working on my end. For my system (without heat utilities), it reported a bug:
<img width="681" alt="Screen Shot 2020-12-05 at 7 01 57 PM" src="https://user-images.githubusercontent.com/49011373/101268733-5b03da80-372c-11eb-93f2-815ae4f8e0a3.png">

For the cornstover system, it changed to another bug:
<img width="681" alt="Screen Shot 2020-12-05 at 7 02 27 PM" src="https://user-images.githubusercontent.com/49011373/101268740-6ce57d80-372c-11eb-8750-6b9898589025.png">

But it worked for the lipidcane system. Can you have a look at this? Thanks!

**Comment by yoelcortes** [comment]
Thanks for reporting this. Yes, this is a bug. When unit operations don't have any design, cost, heat_utilities, and power utilities, they don't return a results table. This is the case for the SteamMixer in the cornstover biorefinery. Only units with a design or cost method are included in tables, so it doesn't happen in the lipidcane biorefinery. I fixed it so that these sort of units are ignored.

**Comment by yoelcortes** [comment]
Made an edit to my reply just make it more clear jaja

**Comment by yalinli2** [comment]
Great the error is gone now! BTW I realized the other bug (about not having include_zeros) is on my side, not biosteam. Thanks!!!
