### ISSUE TITLE
Improve Model.evaluate function

### ISSUE THREAD

**Issue by yalinli2** [BioSTEAMDevelopmentGroup/biosteam#44]
Hope you aren't mad at me bringing this up again haha, but let's consider two scenarios:

1. I ran 1,000 Monte Carlo, only 1 or 2 failed. In this case, I don't care too much about the failed scenarios, so now how biosteam handles this, which resets the system and goes on with the evaluation works perfect.

2. I ran 1,000 Monte Carlo, but all of them failed. In this case, there probably was something wrong with my `Model` setup, so I would actually want to see the error message.

So to address both scenarios, I propose:

1. Include an "error_log" attribute to `Model` or `Model.table` to record the error messages.

2. Include a kwarg for the `evaluate` function to allow users to choose whether they want the evaluation to be interrupted by errors.

Glad to discuss and thanks for considering!

**Comment by yoelcortes** [comment]
Hi Yalin, 

Whether 5, 10, or 1000 evaluations failed may or may not be of concern, but flexibility and control in how errors are handled would be nice. 

Thanks for your suggestions. Here are a few of my thoughts:
1. I have tried error logs before and they were not terribly useful... if the traceback is not included, its hard to discern much about the error. It's also odd to go back with a scenario index and think about why did that scenario fail using the error log. 
2. I think a `kwarg` to decide whether the system is interrupted by errors may be useful, but I would like to take this a step further. Perhaps the user could decide what to do given information about the scenario and the exception.

Here is my solution. An `exception_hook` kwarg decides what to do when an evaluation fails. The exception hook is a function called after a failed evaluation. The exception hook should return either None or metric values given an exception and the sample.

Here are a couple of use cases:

```python
import biosteam as bst
import pytest
from biorefineries import lipidcane as lc
from chaospy import distributions as shape
from warnings import simplefilter
import numpy as np
simplefilter("ignore")
IRR_metric = bst.Metric('Internal rate of return', lc.lipidcane_tea.solve_IRR)
metrics = [IRR_metric]
lipidcane_model = bst.Model(lc.lipidcane_sys, metrics)
baseline = lc.lipidcane.F_mass
distribution = shape.Triangle(-baseline , baseline , 2*baseline ) # Negative value should fail

@lipidcane_model.parameter(element=lc.lipidcane, distribution=distribution, units='kg/hr')
def set_lipidcane_flow_rate(flow_rate):
    lc.lipidcane.F_mass =flow_rate

samples = lipidcane_model.sample(15, 'L')
lipidcane_model.load_samples(samples)

# Without an exception hook, the same behavior will result (NaN values for failed evaluations)
lipidcane_model.evaluate()
assert np.isnan(lipidcane_model.table.values).any()

InfeasibleRegion = bst.exceptions.InfeasibleRegion

# This will provide a more understandable solution for infeasible regions
def exception_hook(model, exception, sample): 
    if isinstance(exception, InfeasibleRegion):
        return [0]
lipidcane_model.exception_hook = exception_hook
lipidcane_model.evaluate()
assert not np.isnan(lipidcane_model.table.values).any()

# This will raise an exception due to negative flow rates
def exception_hook(model, exception, sample): 
    if isinstance(exception, InfeasibleRegion):
        raise exception
lipidcane_model.exception_hook = exception_hook
with pytest.raises(InfeasibleRegion): lipidcane_model.evaluate()

# This will raise an exception regardless
def exception_hook(model, exception, sample): 
    raise exception
lipidcane_model.exception_hook = exception_hook
with pytest.raises(InfeasibleRegion): lipidcane_model.evaluate()

# Here is another cool thing we could do in the case where 
# some metrics are expected to fail
bad_metric = bst.Metric('bad metric', lambda: 1/0)
lipidcane_model.metrics = (IRR_metric, bad_metric)
lipidcane_model.load_samples(samples) # Metrics changed, so need to reload sample
def exception_hook(model, exception, sample): 
    if not isinstance(exception, ZeroDivisionError): return
    lc.lipidcane_sys.simulate()
    values = []
    for i in model.metrics:
        try: x = i()
        except: x = None
        values.append(x)
    return x
lipidcane_model.exception_hook = exception_hook
lipidcane_model.evaluate()
bad_metric_results = lipidcane_model.table[bad_metric.index]
IRR_metric_results = lipidcane_model.table[IRR_metric.index]
assert np.isnan(bad_metric_results).all()
assert np.isnan(IRR_metric_results).all()
```

I went ahead and already added this new functionality in BioSTEAM. This is actually the test for the model exception hook in BioSTEAM. 

Hope this helps,
Thanks!

**Comment by yalinli2** [comment]
Oh the `exception_hook` is cool! It's not that straightforward but has much more flexibility. I'll play around with it 😃  Thanks as always!

**Comment by yoelcortes** [comment]
@yalinli2, I removed the model argument from the exception_hook for simplification (sorry if you have to git pull again)

**Comment by yoelcortes** [comment]
> 
> 
> Oh the `exception_hook` is cool! It's not that straightforward but has much more flexibility. I'll play around with it 😃 Thanks as always!

Thanks! Yeah, the use cases I made up are not straight forward, but the hook itself shouldn't be too hard to use... it just takes in two parameters now, the exception and the sample at which it occurred.
