### ISSUE TITLE
Feature Request: MultiEffectEvaporator with number of effects adjusted automatically to achieve given vapor fraction

### ISSUE THREAD

**Issue by sarangbhagwat** [BioSTEAMDevelopmentGroup/biosteam#45]
With MultiEffectEvaporator units, some of you may have noticed that at low input values for vapor fraction (V) we get an infeasible region error. Since this is not true for Flash units, I reasoned that this was not a Thermosteam issue and that the problem could be addressed within the MultiEffectEvaporator class. After discussing this with Yoel, we came to the conclusion that the infeasible region errors at low values of V are due to lower pressure effect(s) being unable to achieve that V at a temperature that is within 5-10 degrees C (hard and fast rule) of the effect immediately preceding it. This is a feature request to address that issue by solving by iteratively removing the effect with the lowest pressure if an infeasible region error occurs with all effects.

E.g., with a MultiEffectEvaporator unit having 5 effects with pressure decreasing from 1st to 5th effect, if an infeasible region error occurs with all 5 effects, a solution is attempted again with the last effect taken off. Repeated if an infeasible region occurs with 4 effects, and so forth.

**Comment by yoelcortes** [comment]
Fixed in biosteam==2.21.10!  Thanks!

**Comment by yoelcortes** [comment]
Adding some details here for context and future reference:

Multi-effect evaporators work by maintaining each effect at a lower pressure than the previous, allowing for heat transfer between the steam produced in one effect with the next. Even if no steam is available for an evaporator, the vacuum pressure forces hot water to boil until the temperature lowers to the saturated temperature. Therefore, there is a minimum fraction of water evaporated for multi-effect evaporators (given by the vacuum pressures of the effects). Removing low-pressure effects allows for a lower fraction of water evaporated.
