### ISSUE TITLE
MEE design

### ISSUE THREAD

**Issue by yalinli2** [BioSTEAMDevelopmentGroup/biosteam#47]
In MEE design, the following line won't work if there is only one evaporator associated with the MEE.

https://github.com/BioSTEAMDevelopmentGroup/biosteam/blob/cca6df548b22c7bbbde10fae68f730f832485355/biosteam/units/_multi_effect_evaporator.py#L405

As evap is defined previously in `for evap in evaporators[1:]`

Related to this, I have a questions regarding the new feature (#45). BioSTEAM now automatically adjusts the number of effects to achieve a given vapor fraction if the set number of effects won't work. But assume I make an MEE with 5 evaporators at V=0.5. In uncertainty analysis,  BioSTEAM finds that 5 evaporators won't work for one simulation and reduce the number to 4, then later, assume that 5 evaporators can work for another simulation, will BioSTEAM reverses the number back to 5?

Thanks!

**Comment by yoelcortes** [comment]
That's right, BioSTEAM would first test whether all 5 effects work (even if previously only 3 effects worked).

Thanks!

**Comment by yoelcortes** [comment]
@yalinli2, if you create a test for this, feel free to post it here and I can add it to biosteam's tests (no worries if not). Thanks!

**Comment by yalinli2** [comment]
> That's right, BioSTEAM would first test whether all 5 effects work (even if previously only 3 effects worked).
> 
> Thanks!

This is great, thanks!

Then to my first question that 
https://github.com/BioSTEAMDevelopmentGroup/biosteam/blob/cca6df548b22c7bbbde10fae68f730f832485355/biosteam/units/_multi_effect_evaporator.py#L405

won't work if there's only one evaporator. Using a slight modified version of MEE's doc:
```python
>>> import biosteam as bst
>>> from biorefineries.cornstover import chemicals
>>> bst.settings.set_thermo(chemicals)
>>> feed = bst.Stream('feed', Water=1000, Glucose=100, 
...                   AceticAcid=0.5, HMF=0.1, Furfural=0.1,
...                   units='kg/hr')
>>> E1 = bst.MultiEffectEvaporator('E1', ins=feed, outs=('solids', 'liquid'), 
...                                V=0.1, V_definition='Overall',
...                                P=(20000,))
>>> E1.simulate()
```
It will reproduce the error. Thanks!

**Comment by yoelcortes** [comment]
Fixed! In addition to this, I also fixed the following corrections:
* Made sure vapor outlet of first evaporator is a gas, so now utility costs are more accurate (higher than before).
* The first effect is model by vapor-liquid equilibrium (more rigorous) and the heat exchanger network can use now integrate heat with the first effect.

These two results balance each other out, hopefully results in your biorefinery didn't change too much.

Thanks!

**Comment by yalinli2** [comment]
Thanks! The problem has been fixed! I did see the changes in results, couldn't recall the exact difference, but didn't seem to be large

Though I want to point out that

> That's right, BioSTEAM would first test whether all 5 effects work (even if previously only 3 effects worked).
> 
> Thanks!

This doesn't seem to be the case. But I managed to work around this by resetting P to the original design (BioSTEAM changes P to match the number of effects, so the P will be different from the originally designated ones if BioSTEAM reduces the number of effects).

Thanks!!

**Comment by yoelcortes** [comment]
@yalinli2, I found the bug and fixed it:

Changed from:
```python
if self.V_definition == 'Overall':
            P = tuple(self.P)
            self.P = list(P)
            for i in range(self._N_evap-1):
                if self._V_overall(0.) > self.V:
                    self.P.pop()
                    self.load_components()
                else:
                    self.P = P
                    break
```

To:
```python
if self.V_definition == 'Overall':
            P = tuple(self.P)
            self.P = list(P)
            for i in range(self._N_evap-1):
                if self._V_overall(0.) > self.V:
                    self.P.pop()
                    self.load_components()
                else:
                    break
            self.P = P
```

This should do the trick. I'll add a couple of tests eventually.

Thanks!

**Comment by yalinli2** [comment]
Yep it did the trick! Thanks!
