### ISSUE TITLE
GUI interface

### ISSUE THREAD

**Issue by allanc1** [BioSTEAMDevelopmentGroup/biosteam#49]
Hi
Biosteam appears to be a very good platform for my research work but I am more comfortable in in a GUI environment (eg Thermoflex) to build models based on Python scripted unit models. I see that this is work in progress and wonder if you could advise an expected timeframe?

Kind regards

Allan

**Comment by yoelcortes** [comment]
Hi Allan,

Creating a GUI for BioSTEAM which supports programmatic development of unit operations is high on my personal list.  It would greatly help in the development process and encourage wide adoption of BioSTEAM... But currently our group is focused on pushing other BioSTEAM products that are more inline with goals at [CABBI](https://cabbi.bio/) and the US Department of Energy. For example, we are currently working on a online/web browser GUI for biorefinery models in the [Bioindustrial-Park](https://github.com/BioSTEAMDevelopmentGroup/Bioindustrial-Park/tree/master/BioSTEAM%202.x.x/biorefineries) that display key metrics under uncertainty and other analyses. The Beta version of this will be out this year.

So to answer your question, a GUI for developing process models in BioSTEAM may take anywhere between 2-4 years. I'm not a UI programmer (yet), so depending whether or not  I find a collaborator, it may be 2 or 4 years.

Please feel free to post any how-to questions or issues you may have on github or send me an email, I'm always happy to help users. 

Thanks!
