### ISSUE TITLE
Minor bug

### ISSUE THREAD

**Issue by yalinli2** [BioSTEAMDevelopmentGroup/biosteam#50]
Ran into this when I was debugging something else...I think in the following line, it should be `not '{type(stream).__name__}'` instead of `not '{type(item).__name__}'`  Thanks!
https://github.com/BioSTEAMDevelopmentGroup/biosteam/blob/e61ab4a27aa4f4463e54197f6d11072326f778c6/biosteam/utils/piping.py#L249

**Comment by yoelcortes** [comment]
Hi Yalin, nice find! Did I mention that you have write access to BioSTEAM? You can push directly to BioSTEAM:

```bash
$ git clone --depth 10 git clone git://github.com/BioSTEAMDevelopmentGroup/biosteam
$ cd biosteam
$ git add . 
$ git commit -m "{message}"
$ git push origin master
```

Why don't you give it a shot with this bug fix?
Feel free to push directly to master often, I can always correct details later (or even reverse commits if really necessary). I think it works much faster than pull requests. Sarang has already made some enhancements in this manner. 

Thanks,
Let me know if you have any questions!

**Comment by yalinli2** [comment]
Great! Just fixed it, will fix minor bugs like this in the future . 

Only I use this to set the depth when cloning:
`git clone git://github.com/BioSTEAMDevelopmentGroup/biosteam --depth 10`, I think you accidentally typed `git clone` twice in the reply.
