### ISSUE TITLE
How to consider the lifetime of equipment if it's different from the biorefinery lifetime?

### ISSUE THREAD

**Issue by yalinli2** [BioSTEAMDevelopmentGroup/biosteam#51]
I'm not sure if we have run into this problem in any of the biorefineries. But suppose we have a biorefinery with a lifetime of 30 years, and we have a piece of equipment that will only last for 15 years. So we'll need to buy another piece of the equipment half way through the project. How can we account for this in TEA?

I don't think we can just multiply the cost by 2 since we need to consider discount, so we probably need to do something to the cashflow table.

Thanks!

**Comment by yoelcortes** [comment]
Yeah, this hasn't been done in BioSTEAM yet. Probably going to need some additional code in the TEA class and some conventions in the Unit class. Maybe we can have an attribute for all unit operations called `equipment_life_time`, an integer for the amount of years it can be used (if None, it cant default to the biorefinery life time when doing TEA). Then we can have some lines of code in the "taxable_and_nontaxable_cashflows" to add entries to the Fixed Capital column. This will take a bit of time as we'll need to create a 1d array of installed equipment cost cashflows for each unit operation, sum them together, then add entries to the "Fixed Capital" column.

I can get this done by the end of the week or sooner.

Thanks!

**Comment by yalinli2** [comment]
Thanks Yoel! This sounds nice, only some minor comments:

- Can we call it `equipment_lifetime`? Looks like it's one word.
  - Is it possible that one unit have different pieces of equipment with different lifetime? Although this will make things a bit more complicated. But maybe we can have a dict like `_BM` with default set to `None`?
- Can we also update the `cost` decorator so lifetime can be easily added?

Thanks!!!

**Comment by yoelcortes** [comment]
Good points; will do!

**Comment by yoelcortes** [comment]
Done! You can check out the `test_unit.py` module in the tests folder for some examples and look at the Unit API or BioSTEAM tutorial for more details.

**Comment by yalinli2** [comment]
Great!!! Thanks for working on this so quickly!
