### ISSUE TITLE
Allow user to set split for Splitter

### ISSUE THREAD

**Issue by yalinli2** [BioSTEAMDevelopmentGroup/biosteam#53]
Currently ``split`` in ``bst.Splitter`` is just a property without setter:
```python
@property
def split(self):
    """[Array] Componentwise split of feed to 0th outlet stream."""
    return self._isplit._data
```
but can we add a setter function to it? Like:
```python
@property
def split(self):
    """[Array] Componentwise split of feed to 0th outlet stream."""
    return self._isplit._data
@split.setter
def split(self, split):
    self._isplit = self.thermo.chemicals.isplit(split)
```
Or we can add a ``set_split`` function to take in the ``order`` arg as in the ``__init__``, thanks!

**Comment by yoelcortes** [comment]
I've been meaning to add a setter, but kept forgetting. Just added it, so this works now:
```python
splitter.split = values
```

Note that splits can be also be set as follows (without a setter):
```python
splitter.split[:] = values
splitter.isplit[key] = values
```

Thanks!

**Comment by yalinli2** [comment]
Cool! Thanks!
