### ISSUE TITLE
Best practice to work around tiny errors

### ISSUE THREAD

**Issue by yalinli2** [BioSTEAMDevelopmentGroup/biosteam#54]
I'm not exactly sure whether it's the problem of Python of numpy, but sometimes numbers such as 0.8 will be expressed as 0.8000000001 (I heard because it's recorded as one number divided by another one?). So this sometimes cause problems in reactions because of the material infeasible check. I'm now adding a "1e-6" to some reaction conversions to work around this, but wondering if there are better ways? Thanks!

**Comment by yoelcortes** [comment]
Hi Yalin, that was pretty much the same thing I used to do to prevent those floating point error that would give tiny negative flows. I updated thermosteam to prevent negligible negative flows. 

If you are using the github version, don't forget to update the free_properties package (I made a minor correction and uploaded a new version on PyPI).

Thanks!

**Comment by yalinli2** [comment]
Cool! Thanks Yoel! I will test it after finishing updating biorefineries and let you know if there are any problems.
