### ISSUE TITLE
NOTICE: Upgrading to Python 3.8

### ISSUE THREAD

**Issue by yoelcortes** [BioSTEAMDevelopmentGroup/biosteam#56]
BioSTEAM will be moving to 3.8 with the next updates.

**Reasons**

* Python 3.8 offers huge, but not backward compatible, advantages such as the walrus operator ([assignment expressions](https://www.python.org/dev/peps/pep-0572/)), [positional-only arguments](https://www.python.org/dev/peps/pep-0570/), the f'{expr=}' syntax for debugging, and much more.  These improvements would accelerate development in BioSTEAM. 

* It has been over a year since Python 3.8 has been released, and all major libraries already support to Python 3.8.

**Comment by yalinli2** [comment]
Hi Yoel, thanks for the notice! I'm on Python 3.7 now, so what will happen if I were to upgrade biosteam? Thanks!

**Comment by yoelcortes** [comment]
Hi Yalin, nothing would happen as of right now, I'll comment once I push the updates (probably later this week), so everyone can now we've moved to Python 3.8. 

I don't think anyone should have any problems with upgrading. All past versions of BioSTEAM also work in 3.8.

Thanks!

**Comment by yalinli2** [comment]
Cool, thanks Yoel!

**Comment by yalinli2** [comment]
Hey Yoel, is biosteam 2.24.1 on Python 3.8 now? I'm still on Python 3.7 but 2.24.1 seems to be fine. I tried to upgrade my Python through [conda](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-python.html), but it threw out 170 pages of conflicts... Any suggestion on how to update Python? Thanks!

**Comment by yoelcortes** [comment]
Hi Yalin, managing dependencies with updating Python is real mess sometimes... I would say uninstall and reinstall anaconda for Python 3.8, then pip install biosteam.  I've kept myself from using backwards incompatible features from Python 3.8, so 3.6 and 3.7 will still work, but not for long jaja

**Comment by yoelcortes** [comment]
@yalin, as you probably notice, BioSTEAM only works with Python 3.8 or higher now. I added the requirement in `setup.py` for PyPI,. I'll update readthedocs and github workflows too, hopefully within a couple of days

**Comment by yalinli2** [comment]
Thanks for the notice!
