### ISSUE TITLE
Question: Is it possible to exclude subsystems

### ISSUE THREAD

**Issue by DmitryBachin** [BioSTEAMDevelopmentGroup/biosteam#57]
As I see biosteam automatically builds subsystems (default id SYS1, SYS2 etc) when the process is too complicated. Is it possible to prevent it to make it? 

Or at least to make biosteam to draw full diagrams, avoiding systems?

**Comment by yoelcortes** [comment]
Hi Dmitry, are you asking about making diagrams? I think you've been using the default 'surface' diagram. Just pass 'thorough' or 'cluster' to the `kind` argument to get full diagrams:

```python
from biosteam import main_flowsheet as f
sys = f.create_system('sys')
sys.diagram('thorough')  # Full diagram, without showing recycle systems
sys.diagram('cluster') # Full diagram with recycle systems boxed and recycle streams appear in red
```

Here is a link to the API:
https://biosteam.readthedocs.io/en/latest/System.html#biosteam.System.diagram

Here are some examples:
https://biosteam.readthedocs.io/en/latest/tutorial/Creating_a_System.html

Hope this helps,
Thanks!

**Comment by yoelcortes** [comment]
One additional thing you could do, is to flatten the system. The flattened system may still converge, but not as fast as the nested one.

```python
from biosteam import main_flowsheet as f
# Create and connect some units here...
sys = f.create_system('sys')
sys.flatten()
sys.diagram()  # No nested systems so it's equivalent to 'thorough'
sys.diagram('cluster')  # All recycle streams will appear in red
```

Thanks!

**Comment by DmitryBachin** [comment]
It works. Thank you very much!
