### ISSUE TITLE
Adjust Monte Carlo sample array

### ISSUE THREAD

**Issue by yalinli2** [BioSTEAMDevelopmentGroup/biosteam#61]
@stetsonrowles raised an interesting issue on setting up `Model` for Monte Carlo analysis. When defining the parameters, say a household size, assume we think it's follows a normal distribution with mu being 4 and sigma being 1.8 (assume we are OK with not being an integer), we know the minimum number should be 1, but when doing:

```python
  D = shape.Normal(mu=4, sigma=1.8)
  @param(name='Household size', element=unit, kind='coupled', units='cap/household',
         baseline=b, distribution=D)
  def set_household_size(i):
      systems.household_size = max(1, i)
```
If `i` is -0.5, we will make the variable `household_size` to be 1, however, in the sample array, `i` would still be recorded as -0.5 and this might cause problem in doing Spearman ranking or other sensitivity analysis. We can of course fix the sample array before doing the analysis, but I'm wondering if it would be worthwhile to allow the users manipulate the samples after getting the array from `chaospy` (like allowing a hook)? Or do you think it'll be best for the users to do this on their own terms? Thanks!

**Comment by yoelcortes** [comment]
Hi Yalin,

This is a good point! I've encountered this problem but never minded it... I would be open to adding an optional "parameter hook" that changes the value of the sample when loaded (so it only happens once).

Here is an example of how I would image this implementation:

```python
  @param(name='Household size', element=unit, kind='coupled', units='cap/household',
         baseline=b, distribution=D, shape.Normal(mu=4, sigma=1.8), hook=lambda x: max(1, x))
  def set_household_size(x):
      systems.household_size = x
```

The hook would only run once when loading the samples, so the new feature would make the code run even faster.
Let me know if you have any more suggestions on this. I'd be happy to implement this feature in the next day or two.

Thanks!

**Comment by yalinli2** [comment]
I like this feature and the way you make it only run when loading the samples, all looks great to me, thanks Yoel! 👏

**Comment by yoelcortes** [comment]
Done! Closing the feature request.

**Comment by yalinli2** [comment]
Thanks Yoel! I see it's working now (haven't been able to take a look until now), tada!
