### ISSUE TITLE
`lazypkg` dependency

### ISSUE THREAD

**Issue by yalinli2** [BioSTEAMDevelopmentGroup/biosteam#74]
I noticed that some biorefineries require `lazypkg` (e.g., [TAL](https://github.com/BioSTEAMDevelopmentGroup/Bioindustrial-Park/blob/master/BioSTEAM%202.x.x/biorefineries/TAL/__init__.py)) but I don't think it's included as a dependency. Do we want to either add it to requirements or remove it from the biorefineries? @yoelcortes @sarangbhagwat Thanks!

BTW, why do we have two TAL biorefineries ([TAL](https://github.com/BioSTEAMDevelopmentGroup/Bioindustrial-Park/blob/master/BioSTEAM%202.x.x/biorefineries/TAL) and [triacetic_acid_lactone](https://github.com/BioSTEAMDevelopmentGroup/Bioindustrial-Park/tree/master/BioSTEAM%202.x.x/biorefineries/triacetic_acid_lactone))?

**Comment by yalinli2** [comment]
@yoelcortes @sarangbhagwat Just to make sure you can see this issue, thanks!

**Comment by sarangbhagwat** [comment]
Thanks Yalin, looking into this now! I think we can change TAL to be independent of lazypkg, and I'm pretty sure triacetic_acid_lactone was a separate folder created by Yoel while we were working on the solubility model, but that's been superseded by the one we implemented in TAL, so we can delete that.

**Comment by yalinli2** [comment]
Sounds great! Thanks Sarang!
