### ISSUE TITLE
How are the utilities of auxiliary units counted?

### ISSUE THREAD

**Issue by yalinli2** [BioSTEAMDevelopmentGroup/biosteam#78]
I'm getting a bit confused with the costs of auxiliary units. I can see that their capital costs are automatically taken into consideration by `_load_auxiliary_capital_costs`, but I'm not sure how their power/heat utilities are considered? 

In the [docs](https://biosteam.readthedocs.io/en/latest/Unit.html#biosteam.Unit.power_utility), it's specifically mentioned that `power_utility` and `heat_utilities` do not include the ones for the auxiliary units, so if I have a `MixTank` with a `Pump` as the auxiliary unit, then how should I consider the power usage of the pump?

Then if we are simulating an HX as an auxiliary unit, are the heat utilities from it automatically accounted for if we use `HeatUtility.sum`?

Thanks!

**Comment by yoelcortes** [comment]
Hi Yalin, 

Ohh no, this is a typo in the docs, the heat_utilities and power_utility objects include all auxiliary units. Only the capital costs are automatically added. Definitely should be warned in the docs as well as double check in unit operations that have auxiliary units.

Thanks for posting this, I'll keep this issue open until it's resolved.

**Comment by yalinli2** [comment]
Phew, sounds great, thanks Yoel!
