### ISSUE TITLE
System.save_report

### ISSUE THREAD

**Issue by yalinli2** [BioSTEAMDevelopmentGroup/biosteam#86]
Hey @yoelcortes , there appears to be a residual `breakpoint` in the code, additionally, can we make it possible to save the system report without graphviz (maybe print a warning about not having graphviz/graphviz not correctly configured)?

https://github.com/BioSTEAMDevelopmentGroup/biosteam/blob/8d00b40a1e9020051075215c98bcca7f966901bc/biosteam/report/table.py#L480

Thank you!

**Comment by yoelcortes** [comment]
Hi Yalin, the system report is already saved even if you dont have graphviz (notice the first try-except-else block with the warning). I'll add a warning that the diagram was made, but couldn't be saved in replace of the breakpoint.

Thanks!

**Comment by yalinli2** [comment]
Sounds great, thanks Yoel!
