### ISSUE TITLE
Question about AgileSystem with Feedstock in another location

### ISSUE THREAD

**Issue by luizmartinocosta** [BioSTEAMDevelopmentGroup/biosteam#92]
Hello,

I am trying to use an AgileSystem to simulate the annual production of an 1G2G system, with two operation modes (in and off season), in which the off season uses only some areas of the process. The motive of some areas being unused is that, during season, the feedstock is sugarcane and on the off-season the plant would operate with bagasse stored from the season period as feedstock for the 2G sector. However, the 2G outlets are connected to the 1G process, for example the destillation sector, so only part of the 1G process is operating.

I tried firstly using the BioSteam's operational flexibility tutorial, but I am receiving errors from units of the unused areas because their inlets don't have mass flow. The problem is that these mass flows are supposed to not exist in the off season, but the units are still "trying to operate", for example a Crushing Mill unit. Is there a way to make some units, and their specifications. inactive only during off season? Or should I try another strategy?

Thanks!

**Comment by yoelcortes** [comment]
Hi Luiz! Absolutely, I think this issue is better fixed internally in BioSTEAM. I will push a solution later today and send let know.

**Comment by luizmartinocosta** [comment]
Thanks for your quick reply!

**Comment by yoelcortes** [comment]
Hi Luiz,

Even if fixing this bug prevents errors with unit operations that have empty feeds, you'll find that some unit operations may have side feeds (like dilution water) and you'll run into the same error. A simple solution to your problem is to just remove the unwanted unit operations:

```python
import biosteam as bst
all_units = list(bst.main_flowsheet.unit)
unwanted_units = {
    # Set of all units you don't want to use
}
subsystem_units = [i for i in all_units if i not in unwanted_units]
subsystem = bst.System.from_units('subsystem', units=subsystem_units)
```

**Comment by luizmartinocosta** [comment]
I tried your solution and it worked here.

Thanks a lot!
