### ISSUE TITLE
Having problems with Energy Balance in AgileSystem

### ISSUE THREAD

**Issue by luizmartinocosta** [BioSTEAMDevelopmentGroup/biosteam#95]
Hello,

I am having some difficulties with the energy balance between two configurations in the AgileSystem and it is kind of related to my last question about feedstock location. When I run the two configurations, there are some duties that are calculated from certain equipments that don't participate in the simulated configuration (I checked that by using the _load_utility_agents function of the BoilerTurbogenerator). I think that the system memorises the mass and energy balances between configurations because they work without problems alone. Is there some way to clear the calculated duties and mass flows of unused units between configurations? Or is it another problem that I may have overlooked while building a subsystem? What I did first was to save the first configuration and then to make a subsystem of the first for the second configuration. With the subsystem, I made the inputs of the units, that previously were connected to now unused units, as None because the AgileSystem ran the second configuration considering the mass flows from the first.

Another question that I have is if I can use the System.N_run() with the AgileSystem to better converge the mass balances, but it is does not affect the system very much. 

Thanks!

**Comment by yoelcortes** [comment]
Hi Luiz, when running an AgileSystem object, each configuration is run separately but the boiler turbogenerator only takes into account the system it is currently being used for. If you simulate just the unit operation (BoilerTurbogenerator) it will assume the system is `<BoilerTurbogenerator>.system`. Using `_load_utility_agents ` will also assume it is servicing `<BoilerTurbogenerator>.system`.

If you'd like to double check this, you can define a `<AgileSystem>.operation_metric` to get any intermediate unit operation results (https://biosteam.readthedocs.io/en/latest/tutorial/Operational_flexibility.html#Agile-sugarcane-and-sweet-sorghum-biorefinery). 

Regarding setting the `<System>.N_run` attribute (not a method). You are welcome to try it. This is useful if you have specifications in the system that affect upstream unit operations. Otherwise, I recommend you use the `<System>.set_tolerance` method to decrease the tolerance convergence (https://biosteam.readthedocs.io/en/latest/System.html#biosteam.System.set_tolerance).

Hope this helps,
THanks!

**Comment by luizmartinocosta** [comment]
Thanks for your reply! Sorry, but I don't know if I understood what is happening with my simulation. I also don't know if it has some relation with my version (2.31.23).

Now I have made a simplified example of what is happening there also using `<AgileSystem>.operation_metric` if it can help to explain. If I run the "more restricted" system first, it calculates a determined steam demand and if I run it following with the "broader" system, both steam demands appear fine. However, if I run them again, the steam demand from the "more restricted" system adds the steam demand from an unused unit of the "broader" one. This steam adding to the "restricted" also happens if I run the "broader" first. If this is expected to happen, then is there a way to reset these adding duties?

Thanks again for your help!

[Test_AgileSystem.zip](https://github.com/BioSTEAMDevelopmentGroup/biosteam/files/8789911/Test_AgileSystem.zip)

**Comment by yoelcortes** [comment]
Hi Luiz, thanks so much for presenting tests and outlining what was the bug. I fixed the bug in the latest commit. The "other_units" attribute was not being updated when the system configurations changed. Anyways, here are the results I get after the fix:
```
Running only the Second Configuration:
utilities from system:
H102 <low_pressure_steam: 3.9e+07 kJ/hr, 1e+03 kmol/hr, 239 USD/hr>
steam mass by mode:
 test2_sys: 18079 kg/hr
---------------------------------------------
Running the Second and then the First Configuration:
utilities from system:
H102 <low_pressure_steam: 3.9e+07 kJ/hr, 1e+03 kmol/hr, 239 USD/hr>
utilities from system:
H101 <low_pressure_steam: 1.06e+07 kJ/hr, 272 kmol/hr, 64.8 USD/hr>
H102 <low_pressure_steam: 2.65e+07 kJ/hr, 682 kmol/hr, 162 USD/hr>
steam mass by mode:
 test2_sys: 18079 kg/hr
 test1_sys: 17186 kg/hr
---------------------------------------------
Running again the Second and then the First Configuration:
utilities from system:
H102 <low_pressure_steam: 3.9e+07 kJ/hr, 1e+03 kmol/hr, 239 USD/hr>
utilities from system:
H101 <low_pressure_steam: 1.06e+07 kJ/hr, 272 kmol/hr, 64.8 USD/hr>
H102 <low_pressure_steam: 2.65e+07 kJ/hr, 682 kmol/hr, 162 USD/hr>
steam mass by mode:
 test2_sys: 18079 kg/hr
 test1_sys: 17186 kg/hr
---------------------------------------------
Running the First and then the Second Configuration:
utilities from system:
H101 <low_pressure_steam: 1.06e+07 kJ/hr, 272 kmol/hr, 64.8 USD/hr>
H102 <low_pressure_steam: 2.65e+07 kJ/hr, 682 kmol/hr, 162 USD/hr>
utilities from system:
H102 <low_pressure_steam: 3.9e+07 kJ/hr, 1e+03 kmol/hr, 239 USD/hr>
steam mass by mode:
 test1_sys: 17186 kg/hr
 test2_sys: 18079 kg/hr
---------------------------------------------
Running only the First Configuration:
utilities from system:
H101 <low_pressure_steam: 1.06e+07 kJ/hr, 272 kmol/hr, 64.8 USD/hr>
H102 <low_pressure_steam: 2.65e+07 kJ/hr, 682 kmol/hr, 162 USD/hr>
steam mass by mode:
 test1_sys: 17186 kg/hr
---------------------------------------------
Running only the Second Configuration:
utilities from system:
H102 <low_pressure_steam: 3.9e+07 kJ/hr, 1e+03 kmol/hr, 239 USD/hr>
steam mass by mode:
 test2_sys: 18079 kg/hr
```

Thanks again!
